name: mobile
description: "A new Flutter project."
version: 0.0.1+1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.1
  timeago: ^3.1.0
  animations: ^2.0.0
  provider: ^6.0.1
  cupertino_icons: ^1.0.6
  just_audio: ^0.9.36
  http: ^1.2.0
  table_calendar: ^3.1.1
  shared_preferences: ^2.0.8
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  intl: ^0.19.0
  uuid: ^4.3.3
  google_sign_in: ^6.2.1
  video_player: ^2.2.11
  audioplayers: ^5.2.1
  image_picker: ^1.1.2
  stop_watch_timer: ^3.1.1
  flutter_dotenv: ^5.1.0
  font_awesome_flutter: ^10.7.0
  omni_datetime_picker: ^1.1.0
  cached_network_image: ^3.3.1
  cached_video_player: ^2.0.4
  collection: ^1.15.0
  flutter_svg: ^2.0.10+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:
  assets:
    - assets/
    - assets/images/
    - assets/images/themes/
    - assets/icons/
    - assets/audios/cafe/
    - assets/audios/nature/
    - assets/videos/
    - .env


  fonts:
    - family: GmarketSansTTFLight
      fonts:
        - asset: assets/fonts/GmarketSansTTFLight.ttf
    - family: GmarketSansTTFMedium
      fonts:
        - asset: assets/fonts/GmarketSansTTFMedium.ttf
  uses-material-design: true
