name: mobile
description: "Distance"
version: 1.0.0+1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.1
  timeago: ^3.1.0
  animations: ^2.0.0
  provider: ^6.0.1
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  table_calendar: ^3.1.1
  shared_preferences: ^2.0.8
  firebase_core: ^2.24.2
  firebase_auth: ^4.0.0
  intl: ^0.19.0
  uuid: ^4.3.3
  google_sign_in: ^6.2.1
  video_player: ^2.2.11
  audioplayers: ^5.2.1
  image_picker: ^1.1.2
  stop_watch_timer: ^3.1.1
  flutter_dotenv: ^5.1.0
  omni_datetime_picker: ^2.0.3
  cached_network_image: ^3.3.1
  cached_video_player: ^2.0.4
  collection: ^1.15.0
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  sleek_circular_slider: ^2.0.1
  emoji_picker_flutter: ^2.2.0
  aws_s3_api: ^2.0.0
  permission_handler: ^11.3.1
  flutter_background_service: ^5.0.6
  background_fetch: ^1.3.5
  kakao_flutter_sdk: ^1.9.5
  crypto: ^3.0.3
  flutter_colorpicker: ^1.1.0
  flutter_native_splash: ^2.4.1
  google_mobile_ads: ^5.1.0
  flutter_cache_manager: ^3.4.0
  audio_service: ^0.18.15
  flutter_image_compress: ^2.3.0
  flutter_local_notifications: ^17.2.1+2
  just_audio: ^0.9.39
  just_audio_background: ^0.0.1-beta.13
  path_provider: ^2.1.4
  url_launcher: ^6.3.0
  app_tracking_transparency: ^2.0.6
  firebase_messaging: ^14.9.4

flutter_native_splash:
  color: "#282828"
  image: "assets/images/splash.png"
  android_12:
    image: "assets/images/splash.png"
    color: "#282828"
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  background_color_ios: "#ffffff"
  image_path: "assets/images/icon.png"
  image_path_ios: "assets/images/ios_icon.png"
  remove_alpha_ios: true

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/images/themes/
    - assets/images/themes/music/
    - assets/audios/nature/
    - .env


  fonts:
    - family: GmarketSansTTFLight
      fonts:
        - asset: assets/fonts/GmarketSansTTFLight.ttf
    - family: GmarketSansTTFMedium
      fonts:
        - asset: assets/fonts/GmarketSansTTFMedium.ttf
    - family: Cafe24OhsquareAir
      fonts:
        - asset: assets/fonts/Cafe24OhsquareAir.ttf
    - family: Cafe24SupermagicRegular
      fonts:
        - asset: assets/fonts/Cafe24SupermagicRegular.ttf
    - family: CormorantGaramondMedium
      fonts:
        - asset: assets/fonts/CormorantGaramondMedium.ttf
    - family: EduAUVICWANTHandRegular
      fonts:
        - asset: assets/fonts/EduAUVICWANTHandRegular.ttf
    - family: GaeguRegular
      fonts:
        - asset: assets/fonts/GaeguRegular.ttf
    - family: NotoSansKRBold
      fonts:
        - asset: assets/fonts/NotoSansKRBold.ttf
    - family: NotoSansKRLight
      fonts:
        - asset: assets/fonts/NotoSansKRLight.ttf
  uses-material-design: true
