name: mobile
description: "A new Flutter project."
version: 0.0.1+1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.1
  timeago: ^3.1.0
  animations: ^2.0.0
  provider: ^6.0.1
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  table_calendar: ^3.1.1
  shared_preferences: ^2.0.8
  firebase_core: ^2.24.2
  firebase_messaging: ^14.9.4
  firebase_auth: ^4.0.0
  intl: ^0.19.0
  uuid: ^4.3.3
  google_sign_in: ^6.2.1
  video_player: ^2.2.11
  audioplayers: ^5.2.1
  image_picker: ^1.1.2
  stop_watch_timer: ^3.1.1
  flutter_dotenv: ^5.1.0
  font_awesome_flutter: ^10.7.0
  omni_datetime_picker: ^2.0.3
  cached_network_image: ^3.3.1
  cached_video_player: ^2.0.4
  collection: ^1.15.0
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  sleek_circular_slider: ^2.0.1
  emoji_picker_flutter: ^2.2.0
  aws_s3_api: ^2.0.0
  permission_handler: ^11.3.1
  flutter_background_service: ^5.0.6
  background_fetch: ^1.3.5
  kakao_flutter_sdk: ^1.9.4
  crypto: ^3.0.3
  flutter_colorpicker: ^1.1.0
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:
  assets:
    - assets/
    - assets/images/
    - assets/images/seas/
    - assets/images/themes/
    - assets/images/themes/music/
    - assets/icons/
    - assets/audios/nature/
    - assets/audios/music/consolation/
    - assets/videos/sea/
    - assets/videos/gomji/
    - assets/videos/
    - .env


  fonts:
    - family: GmarketSansTTFLight
      fonts:
        - asset: assets/fonts/GmarketSansTTFLight.ttf
    - family: GmarketSansTTFMedium
      fonts:
        - asset: assets/fonts/GmarketSansTTFMedium.ttf
  uses-material-design: true
