import 'package:mobile/model/quote_model.dart';
final List<Quote> quotes = [
  Quote(writer: "벤자민 프랭클린", quote: "오늘 할 수 있는 일을 내일로 미루지 말라."),
  Quote(writer: "토마스 풀러", quote: "게으름은 부끄러운 것이다. 부지런함은 영예로운 것이다."),
  Quote(writer: "라와나 블랙웰", quote: "나이가 성숙을 보장하지는 않는다."),
  Quote(writer: "헨리 비처", quote: "배우는 것만이 젊음을 연장할 수 있는 길이다."),
  Quote(writer: "공자", quote: "허물이 있다면 버리기를 두려워 말라."),
  Quote(writer: "넬슨 만델라", quote: "인생에서 가장 큰 영광은 넘어지지 않는 것에 있는 것이 아니라 매번 일어선다는 데 있다."),
  Quote(writer: "칭기즈칸", quote: "행동의 가치는 그 행동을 끝까지 이루는 데 있다."),
  Quote(writer: "헬렌 켈러", quote: "고개 숙이지 마십시오. 세상을 똑바로 정면으로 바라보십시오."),
  Quote(writer: "인디언 격언", quote: "그대 자신의 영혼을 탐구하라. 다른 누구에게도 의지하지 말고 오직 그대 혼자의 힘으로 하라."),
  Quote(writer: "존 웨인", quote: "용기란 죽을 만큼 두려워도 일단 한 번 해보는 것이다."),
  Quote(writer: "캐롤 버넷", quote: "내 인생을 바꾸는 사람은 자신입니다. 아무도 대신해줄 수 없어요."),
  Quote(writer: "빈스롬바디", quote: "승리는 습관이다. 불행히도 패배도 그렇다."),
  Quote(writer: "빌 게이츠", quote: "인생은 불공평합니다. 익숙해지세요."),
  Quote(writer: "테오프라스토스", quote: "시간은 인간이 쓸 수 있는 가장 값진 것이다."),
  Quote(writer: "마크 트웨인", quote: "삶에 필요한 것은 무지와 자신감이다. 그렇다면 성공은 확실하다."),
  Quote(writer: "박지성", quote: "언젠가 그들도 한 번쯤은 쉴 것이고, 그 때 내가 쉬지 않고 나아간다면 차이가 조금이라도 줄어들겠죠."),
  Quote(writer: "카말 라비칸트", quote: "인생은 내면으로부터 나온다. 당신이 내면을 바꿀 때, 삶은 외부로 바뀐다."),
  Quote(writer: "파울로 코엘료", quote: "언제나 현재에 집중할 수 있다면 행복할 것이다."),
  Quote(writer: "릴리 퓰리처", quote: "일기예보에도 불구하고, 봄처럼 살아라."),
  Quote(writer: "마크 트웨인", quote: "당신의 인생에서 가장 중요한 두 날은 당신이 태어난 날과 그 이유를 찾는 날이다."),
  Quote(writer: "알베르 카뮈", quote: "두려움 때문에 갖는 존경심만큼 비열한 것은 없다."),
  Quote(writer: "오프라 윈프리", quote: "상처를 지혜로 바꾸세요."),
  Quote(writer: "엘론 머스크", quote: "당신이 포기할 때 나는 시작한다."),
  Quote(writer: "윈스턴 처칠", quote: "성공은 종점이 아니며, 실패는 치명적이지 않습니다. 중요한 것은 용기입니다."),
  Quote(writer: "헨리 데이비드 소로", quote: "성공은 보통 바빠서 찾아갈 시간이 없는 사람들의 것이다."),
  Quote(writer: "제임스 딘", quote: "평생 살 것처럼 꿈을 꾸어라. 그리고 내일 죽을 것처럼 오늘을 살아라."),
  Quote(writer: "존 D. 록펠러 주니어", quote: "성공의 비결은 평범하지 않은 일을 잘 하는 것이다."),
  Quote(writer: "존 D. 록펠러", quote: "더 나은 것을 위해 좋은 것을 포기하는 걸 두려워 하지 마라."),
  Quote(writer: "헨리 포드", quote: "네가 할 수 있다고 생각하든 할 수 없다고 생각하든 네 생각이 옳다."),
  Quote(writer: "벤자민 프랭클린", quote: "실천이 말보다 낫다."),
];
