import 'package:mobile/model/quote_model.dart';
final List<Quote> quotes = [
  Quote(writer: "공자", quote: "허물이 있다면 버리기를 두려워 말라."),
  Quote(writer: "공자", quote: "늘 행복하고 지혜로운 사람이 되려면 자주 변해야 한다."),
  Quote(writer: "라와나 블랙웰", quote: "나이가 성숙을 보장하지는 않는다."),
  Quote(writer: "라와나 블랙웰", quote: "젊음은 반드시 칭송되는 것만큼 좋은 것은 아니다."),
  Quote(writer: "마야 안젤루", quote: "인생에서 많은 패배에 직면하겠지만 결코 패배하지 말라."),
  Quote(writer: "넬슨 만델라", quote: "인생에서 가장 큰 영광은 넘어지지 않는 것에 있는 것이 아니라 매번 일어선다는 데 있다."),
  Quote(writer: "헬렌켈러", quote: "생활은 과감한 모험이거나 아니면 아무것도 아니다."),
  Quote(writer: "제노", quote: "자연과 조화롭게 살아가는 것이 삶의 목적이다."),
  Quote(writer: "에트 hunpw시비트", quote: "이또한 지나가리라."),
  Quote(writer: "줄리어스 시저", quote: "주사위는 던져졌다."),
  Quote(writer: "캐롤 버넷", quote: "내 인생을 바꾸는 사람은 자신입니다. 아무도 대신해줄 수 없어요."),
  Quote(writer: "릴리 렁", quote: "의심이 있다면, 변화해라."),
  Quote(writer: "빌 게이츠", quote: "인생은 불공평합니다. 익숙해지세요."),
  Quote(writer: "빌리 퓰리처", quote: "즐거움은 영원히 유행에 뒤떨어지지 않는다."),
  Quote(writer: "마크 트웨인", quote: "삶에 필요한 것은 무지와 자신감이다. 그렇다면 성공은 확실하다."),
  Quote(writer: "막심 라가세", quote: "인생은 산이다. 당신의 목표는 정상에 도달하는 것이 아니라 당신의 길을 찾는 것이다."),
  Quote(writer: "카말 라비칸트", quote: "인생은 내면으로부터 나온다. 당신이 내면을 바꿀 때, 삶은 외부로 바뀐다."),
  Quote(writer: "쇠렌 키에르케고르", quote: "인생은 거꾸로만 이해되지만 앞으로 살아야 한다."),
  Quote(writer: "릴리 퓰리처", quote: "일기예보에도 불구하고, 봄처럼 살아라."),
  Quote(writer: "마크 트웨인", quote: "당신의 인생에서 가장 중요한 두 날은 당신이 태어난 날과 그 이유를 찾는 날이다."),
  Quote(writer: "알베르 카뮈", quote: "두려움 때문에 갖는 존경심만큼 비열한 것은 없다."),
  Quote(writer: "오프라 윈프리", quote: "상처를 지혜로 바꾸세요."),
  Quote(writer: "바버라 부시", quote: "성공의 가장 중요한 기준이 다른 사람들을 어떻게 대하느냐라는 것이다."),
  Quote(writer: "윈스턴 처칠", quote: "성공은 종점이 아니며, 실패는 치명적이지 않습니다. 중요한 것은 용기입니다."),
  Quote(writer: "헨리 데이비드 소로", quote: "성공은 보통 바빠서 찾아갈 시간이 없는 사람들의 것이다."),
  Quote(writer: "스티브 JOBS", quote: "만약 당신이 정말로 자세히 관찰한다면, 대부분의 하룻밤 동안의 성공에는 많은 시간이 걸린 것을 발견할 것이다."),
  Quote(writer: "존 D. 록펠러 주니어", quote: "성공의 비결은 평범하지 않은 일을 잘 하는 것이다."),
  Quote(writer: "존 D. 록펠러", quote: "더 나은 것을 위해 좋은 것을 포기하는 걸 두려워 하지 마라."),
  Quote(writer: "윈스턴 처칠", quote: "성공은 실패에서 실패로, 열정을 잃지 않는 것이다."),
  Quote(writer: "G.K 체스터턴", quote: "나의 성공은 최고의 조언을 듣고 떠나 정반대의 일을 한 덕분이다."),
];
